#!/bin/bash
if [ "$EUID" -ne 0 ]; then
        echo "Please run as root"
        exit
fi

mkdir "/var/www/html/$1"
mkdir "/var/log/apache2/$1"

echo    "<VirtualHost *:80>
               ServerName $1
               DocumentRoot "/var/www/html/$1"
               ErrorLog "/var/log/apache2/$1"/error.log
               CustomLog "/var/log/apache2/$1"/access.log combined
        </VirtualHost>" > "/etc/apache2/sites-available/$1.conf"

sub=$(echo $1 | grep -oP ".+(?=(\.sam-janssens))")
echo  "welcome $sub" > "/var/www/html/$1/index.html"
	
echo "$sub	IN	A	193.191.177.175" >> "/etc/bind/zones/db.sam-janssens.sb.uclllabs.be"

serial_nr=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/zones/db.sam-janssens.sb.uclllabs.be)	
serial_comp=$(grep -Po '\d+\s+; Serial' /etc/bind/zones/db.sam-janssens.sb.uclllabs.be)
serial_ln=$(grep -Po '\s+; Serial' /etc/bind/zones/db.sam-janssens.sb.uclllabs.be)
serial_updated=$(("$serial_nr" + 1))

sed -i "s/$serial_comp/$serial_updated$serial_ln/g" /etc/bind/zones/db.sam-janssens.sb.uclllabs.be
systemctl restart bind9

a2ensite $1 > /dev/null
systemctl reload apache2
